# fly.toml file generated for noodle on 2021-04-19T14:54:58-04:00

app = "noodle"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[[services]]
  http_checks = []
  internal_port = 8082
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 80

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
